modLoader="javafml"
license="MIT"
issueTrackerURL="https://github.com/TreyRuffy/ProjectAuroraMinecraftMod/issues"

loaderVersion="*"

[[mods]]
modId="project_aurora_minecraft_mod"
version="${version}"
displayName="Project Aurora Minecraft Mod"
updateJSONURL="https://api.modrinth.com/updates/project-aurora-minecraft-mod/forge_updates.json"
displayURL="https://modrinth.com/mod/project-aurora-minecraft-mod"
logoFile="icon.png"
authors="TreyRuffy"
description='''
Project Aurora Minecraft Mod for Minecraft Forge
Game State Integration server designed for Aurora (but could be used by other applications).

The creator would like to thank:
- Wibble199 for originally creating the mod
'''

[[mixins]]
config = "project-aurora-common.mixins.json"

[[dependencies.project_aurora_minecraft_mod]]
modId="minecraft"
mandatory=true
ordering="NONE"
side="CLIENT"
versionRange="[1.21,)"

[[dependencies.project_aurora_minecraft_mod]]
modId="kotlinforforge"
mandatory=true
ordering="NONE"
side="BOTH"
versionRange="*"
